
export const FooterData = [
    {
        category:"Category1",
        links:[
            {
                link:"Link1",
                to:"/"
            },
            {
                link:"Link2",
                to:"/"
            },
            {
                link:"Link3",
                to:"/"
            },
            {
                link:"Link4",
                to:"/"
            },
        ]
    },
    {
        category:"Category2",
        links:[
            {
                link:"Link1",
                to:"/"
            },
            {
                link:"Link2",
                to:"/"
            },
            {
                link:"Link3",
                to:"/"
            },
            {
                link:"Link4",
                to:"/"
            },
        ]
    },
    {
        category:"Category3",
        links:[
            {
                link:"Link1",
                to:"/"
            },
            {
                link:"Link2",
                to:"/"
            },
            {
                link:"Link3",
                to:"/"
            },
            {
                link:"Link4",
                to:"/"
            },
        ]
    },
    {
        category:"Category4",
        links:[
            {
                link:"Link1",
                to:"/"
            },
            {
                link:"Link2",
                to:"/"
            },
            {
                link:"Link3",
                to:"/"
            },
            {
                link:"Link4",
                to:"/"
            },
        ]
    },
]